/**
 * demo fixtures shown when DATABASE_URL is not configured, so the dashboard
 * is reviewable without postgres. clearly marked in the ui.
 */
import type {
  ApprovalDraftView,
  PreferencesView,
  ScheduledEventView,
  UpcomingSessionView,
} from "./types";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const now = () => Date.now();

export function demoUpcoming(): UpcomingSessionView[] {
  return [
    {
      id: "demo-session-1",
      contactName: "maya chen",
      state: "awaiting_user_approval",
      stateLabel: "draft waiting for your review",
      category: "needs_user",
      meetingType: "coffee",
      durationMinutes: 45,
      meetingFormat: "in_person",
      location: "blue bottle, hayes valley",
      waitingOn: "user",
      lastMessageText: "coffee soon? been too long",
      lastMessageDirection: "inbound",
      lastMessageAtIso: new Date(now() - 2 * HOUR).toISOString(),
      nextFollowUpAtIso: null,
      followUpAttemptCount: 0,
      followUpMaxAttempts: 3,
      candidateTimes: [
        {
          id: "demo-slot-1",
          startsAtIso: new Date(now() + 2 * DAY + 14 * HOUR).toISOString(),
          endsAtIso: new Date(now() + 2 * DAY + 14.75 * HOUR).toISOString(),
          timezone: "America/New_York",
          status: "candidate",
        },
        {
          id: "demo-slot-2",
          startsAtIso: new Date(now() + 3 * DAY + 10 * HOUR).toISOString(),
          endsAtIso: new Date(now() + 3 * DAY + 10.75 * HOUR).toISOString(),
          timezone: "America/New_York",
          status: "candidate",
        },
      ],
      bundle: null,
      warnings: [],
      professional: true,
      snoozedUntilIso: null,
      updatedAtIso: new Date(now() - HOUR).toISOString(),
    },
    {
      id: "demo-session-2",
      contactName: "priya patel",
      state: "follow_up_due",
      stateLabel: "follow-up due today",
      category: "follow_up_due",
      meetingType: "quick_call",
      durationMinutes: 15,
      meetingFormat: "phone",
      location: null,
      waitingOn: "system",
      lastMessageText: "let me check my week and get back to you",
      lastMessageDirection: "inbound",
      lastMessageAtIso: new Date(now() - 2 * DAY).toISOString(),
      nextFollowUpAtIso: new Date(now() + 3 * HOUR).toISOString(),
      followUpAttemptCount: 1,
      followUpMaxAttempts: 2,
      candidateTimes: [],
      bundle: null,
      warnings: [],
      professional: true,
      snoozedUntilIso: null,
      updatedAtIso: new Date(now() - 5 * HOUR).toISOString(),
    },
    {
      id: "demo-session-3",
      contactName: "sam okafor",
      state: "waiting_for_attendee",
      stateLabel: "waiting for their reply",
      category: "waiting_attendee",
      meetingType: "dinner",
      durationMinutes: 90,
      meetingFormat: "in_person",
      location: null,
      waitingOn: "attendee",
      lastMessageText: "dinner next week? i could do tuesday or wednesday evening",
      lastMessageDirection: "outbound",
      lastMessageAtIso: new Date(now() - 6 * HOUR).toISOString(),
      nextFollowUpAtIso: new Date(now() + 2 * DAY).toISOString(),
      followUpAttemptCount: 0,
      followUpMaxAttempts: 3,
      candidateTimes: [],
      bundle: {
        id: "demo-bundle-1",
        messagesUsed: 1,
        maximumOutboundMessages: 3,
        expiresAtIso: new Date(now() + 18 * HOUR).toISOString(),
        status: "active",
      },
      warnings: [],
      professional: false,
      snoozedUntilIso: null,
      updatedAtIso: new Date(now() - 6 * HOUR).toISOString(),
    },
    {
      id: "demo-session-4",
      contactName: "leo martin",
      state: "waiting_for_follow_up",
      stateLabel: "follow-up scheduled",
      category: "follow_up_scheduled",
      meetingType: "meeting",
      durationMinutes: 30,
      meetingFormat: "virtual",
      location: null,
      waitingOn: "attendee",
      lastMessageText: "sent a couple of times for the roadmap sync",
      lastMessageDirection: "outbound",
      lastMessageAtIso: new Date(now() - 1 * DAY).toISOString(),
      nextFollowUpAtIso: new Date(now() + 3 * DAY).toISOString(),
      followUpAttemptCount: 1,
      followUpMaxAttempts: 3,
      candidateTimes: [],
      bundle: null,
      warnings: ["mac needs to reconnect — last seen 26 hours ago"],
      professional: true,
      snoozedUntilIso: null,
      updatedAtIso: new Date(now() - DAY).toISOString(),
    },
    {
      id: "demo-session-5",
      contactName: "ana silva",
      state: "paused",
      stateLabel: "paused",
      category: "snoozed",
      meetingType: "lunch",
      durationMinutes: 60,
      meetingFormat: "in_person",
      location: null,
      waitingOn: null,
      lastMessageText: "let's pick this up after my trip",
      lastMessageDirection: "inbound",
      lastMessageAtIso: new Date(now() - 4 * DAY).toISOString(),
      nextFollowUpAtIso: null,
      followUpAttemptCount: 0,
      followUpMaxAttempts: null,
      candidateTimes: [],
      bundle: null,
      warnings: [],
      professional: false,
      snoozedUntilIso: new Date(now() + 5 * DAY).toISOString(),
      updatedAtIso: new Date(now() - 4 * DAY).toISOString(),
    },
  ];
}

export function demoApprovals(): ApprovalDraftView[] {
  return [
    {
      id: "demo-draft-1",
      sessionId: "demo-session-1",
      contactName: "maya chen",
      objective: "propose_slots",
      objectiveLabel: "proposing times",
      proposedText:
        "would love to! i could do thursday 2pm or friday 10am — either work?",
      alternativeTexts: ["yes! thursday 2pm or friday 10am work on my end"],
      contextSummary: "maya asked to grab coffee. both of you agreed to meet.",
      candidateTimes: [
        {
          id: "demo-slot-1",
          startsAtIso: new Date(now() + 2 * DAY + 14 * HOUR).toISOString(),
          endsAtIso: new Date(now() + 2 * DAY + 14.75 * HOUR).toISOString(),
          timezone: "America/New_York",
          status: "candidate",
        },
        {
          id: "demo-slot-2",
          startsAtIso: new Date(now() + 3 * DAY + 10 * HOUR).toISOString(),
          endsAtIso: new Date(now() + 3 * DAY + 10.75 * HOUR).toISOString(),
          timezone: "America/New_York",
          status: "candidate",
        },
      ],
      confidence: 0.91,
      expiresAtIso: new Date(now() + 22 * HOUR).toISOString(),
      meetingType: "coffee",
      durationMinutes: 45,
    },
    {
      id: "demo-draft-2",
      sessionId: "demo-session-2",
      contactName: "priya patel",
      objective: "follow_up",
      objectiveLabel: "following up",
      proposedText: "hey! any luck with your week? happy to send a few new times too",
      alternativeTexts: [],
      contextSummary:
        "priya said she'd check her week two days ago. first follow-up of two.",
      candidateTimes: [],
      confidence: 0.84,
      expiresAtIso: new Date(now() + 8 * HOUR).toISOString(),
      meetingType: "quick_call",
      durationMinutes: 15,
    },
  ];
}

export function demoScheduled(): ScheduledEventView[] {
  return [
    {
      sessionId: "demo-session-6",
      title: "roadmap sync",
      attendeeName: "leo martin",
      startsAtIso: new Date(now() + 4 * DAY + 15 * HOUR).toISOString(),
      endsAtIso: new Date(now() + 4 * DAY + 15.5 * HOUR).toISOString(),
      timezone: "America/New_York",
      location: null,
      meetingFormat: "virtual",
      calendarName: "personal",
      calendarEventId: "demo-google-event-id-0001",
      status: "confirmed",
    },
    {
      sessionId: "demo-session-7",
      title: "coffee with jordan lee",
      attendeeName: "jordan lee",
      startsAtIso: new Date(now() + 6 * DAY + 11 * HOUR).toISOString(),
      endsAtIso: new Date(now() + 6 * DAY + 11.75 * HOUR).toISOString(),
      timezone: "America/New_York",
      location: "sightglass, soma",
      meetingFormat: "in_person",
      calendarName: "personal",
      calendarEventId: "demo-google-event-id-0002",
      status: "pending_invite",
    },
  ];
}

export function demoPreferences(): PreferencesView {
  return {
    timezone: "America/New_York",
    approvalMode: "approve_every",
    triggerEmoji: "⏳",
    followUpDefaultEnabled: true,
    workingHours: [1, 2, 3, 4, 5].map((weekday) => ({
      weekday,
      start: "09:00",
      end: "18:00",
    })),
    minimumNoticeMinutes: 120,
    maximumMeetingsPerDay: 8,
    weekendEnabled: false,
    videoDefault: "meet",
    destinationCalendarId: "primary",
    styleMode: "adaptive",
    followUpIntervalHours: [48, 120, 240],
    quietHours: { earliest: "09:00", latest: "19:00" },
    connections: {
      google: { status: "not_connected", email: null, lastSyncIso: null },
      mac: {
        status: "not_paired",
        deviceName: null,
        lastSeenIso: null,
        messagesPermission: "unknown",
        appVersion: null,
      },
    },
  };
}
